/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CONTROLLER.LoginController;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Andre
 */
public class LogInView extends javax.swing.JFrame
{
    //Cria a propriedade controller:
    private final LoginController controller;

    /**
     * Creates new form LogInView
     */
    public LogInView()
    {
        initComponents();
        
        //no construtor ja definir o controller: e passar a View
        controller = new LoginController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        LabelTituloLogin = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        jTextFileldUsuario = new javax.swing.JTextField();
        LabelSenha = new javax.swing.JLabel();
        jPasswordFileldSenha = new javax.swing.JPasswordField();
        ButtonCadastrar = new javax.swing.JButton();
        ButtonEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTituloLogin.setFont(new java.awt.Font("Courier 10 Pitch", 1, 48)); // NOI18N
        LabelTituloLogin.setForeground(new java.awt.Color(0, 153, 255));
        LabelTituloLogin.setText("Login");
        jPanel1.add(LabelTituloLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        LabelUsuario.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(0, 153, 255));
        LabelUsuario.setText("Usuario");
        jPanel1.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jTextFileldUsuario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFileldUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFileldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 400, 40));

        LabelSenha.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        LabelSenha.setForeground(new java.awt.Color(0, 153, 255));
        LabelSenha.setText("Senha");
        jPanel1.add(LabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jPasswordFileldSenha.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jPasswordFileldSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordFileldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 400, 40));

        ButtonCadastrar.setBackground(new java.awt.Color(164, 152, 152));
        ButtonCadastrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ButtonCadastrar.setText("Cadastrar");
        ButtonCadastrar.setActionCommand("ButtonEntrar");
        ButtonCadastrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 190, 50));

        ButtonEntrar.setBackground(new java.awt.Color(164, 152, 152));
        ButtonEntrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ButtonEntrar.setText("Entrar");
        ButtonEntrar.setActionCommand("ButtonEntrar");
        ButtonEntrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 190, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFileldUsuarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFileldUsuarioActionPerformed
    {//GEN-HEADEREND:event_jTextFileldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFileldUsuarioActionPerformed

    private void jPasswordFileldSenhaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jPasswordFileldSenhaActionPerformed
    {//GEN-HEADEREND:event_jPasswordFileldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFileldSenhaActionPerformed

    private void ButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ButtonCadastrarActionPerformed
    {//GEN-HEADEREND:event_ButtonCadastrarActionPerformed
        FormCadastroView telaDeCadastro = new FormCadastroView();
        telaDeCadastro.setVisible(true);        

    }//GEN-LAST:event_ButtonCadastrarActionPerformed

    private void ButtonEntrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ButtonEntrarActionPerformed
    {//GEN-HEADEREND:event_ButtonEntrarActionPerformed
        //Logica de autenticar foi para o controller:
        controller.autenticar();
        
    }//GEN-LAST:event_ButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new LogInView().setVisible(true);
            }
        });
    }

    public JPasswordField getjPasswordFileldSenha()
    {
        return jPasswordFileldSenha;
    }

    public void setjPasswordFileldSenha(JPasswordField jPasswordFileldSenha)
    {
        this.jPasswordFileldSenha = jPasswordFileldSenha;
    }

    public JTextField getjTextFileldUsuario()
    {
        return jTextFileldUsuario;
    }

    public void setjTextFileldUsuario(JTextField jTextFileldUsuario)
    {
        this.jTextFileldUsuario = jTextFileldUsuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrar;
    private javax.swing.JButton ButtonEntrar;
    private javax.swing.JLabel LabelSenha;
    private javax.swing.JLabel LabelTituloLogin;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFileldSenha;
    private javax.swing.JTextField jTextFileldUsuario;
    // End of variables declaration//GEN-END:variables
}
